-- CREATE DATABASE & SCHEMAS
CREATE OR REPLACE DATABASE CUSTOMER360_DW;
CREATE OR REPLACE SCHEMA CUSTOMER360_DW.STAGING;
CREATE OR REPLACE SCHEMA CUSTOMER360_DW.CORE;

-- CREATE FILE FORMAT
CREATE OR REPLACE FILE FORMAT CUSTOMER360_DW.STAGING.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');


-- CREATE INTERNAL STAGE FOR FILE UPLOADING
CREATE OR REPLACE STAGE CUSTOMER360_DW.STAGING.RAW_STAGE
    FILE_FORMAT = CUSTOMER360_DW.STAGING.CSV_FORMAT;


