TRUNCATE TABLE CUSTOMER360_DW.STAGING.stg_customers;
TRUNCATE TABLE CUSTOMER360_DW.STAGING.stg_products;


COPY INTO CUSTOMER360_DW.STAGING.STG_CUSTOMERS
FROM @CUSTOMER360_DW.STAGING.RAW_STAGE/customers_day1.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER360_DW.STAGING.CSV_FORMAT);

COPY INTO CUSTOMER360_DW.STAGING.STG_PRODUCTS
FROM @CUSTOMER360_DW.STAGING.RAW_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER360_DW.STAGING.CSV_FORMAT);


