TRUNCATE TABLE CUSTOMER360_DW.STAGING.stg_customers;

COPY INTO CUSTOMER360_DW.STAGING.STG_CUSTOMERS
FROM @CUSTOMER360_DW.STAGING.RAW_STAGE/customers_day2.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER360_DW.STAGING.CSV_FORMAT);


